name: PDF Rain Areas Page

permissions:
  contents: write

on:
  schedule:
    # Runs at the top of every hour.
    - cron: '0 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  pdf_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Puppeteer
        run: |
          npm init -y
          npm install puppeteer

      - name: Create PDF script
        run: |
          mkdir -p scripts
          cat > scripts/pdf.js << 'EOF'
          const puppeteer = require('puppeteer');
          
          (async () => {
            // Launch browser with necessary flags for CI environments
            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            
            // Navigate to the NEA Rain Areas page
            await page.goto('https://www.nea.gov.sg/weather/rain-areas', { waitUntil: 'networkidle2' });
            
            // Create a timestamp for the filename in UTC
            const now = new Date();
            const isoString = now.toISOString().split('.')[0].replace(/:/g, "-") + "Z";
            const filePath = `pdf_archive/rain-areas-${isoString}.pdf`;
            
            // Generate a PDF of the page in A4 format
            await page.pdf({ path: filePath, format: 'A4' });
            console.log(`PDF saved as ${filePath}`);
            await browser.close();
          })().catch(err => {
            console.error(err);
            process.exit(1);
          });
          EOF

      - name: Create pdf_archive directory
        run: mkdir -p pdf_archive

      - name: Run PDF script
        run: node scripts/pdf.js

      - name: Commit and push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf_archive/
          git commit -m "Add rain areas PDF: $(date -u +'%Y-%m-%dT%H-%M-%SZ')" || echo "No changes to commit"
          git push
